language: node_js
node_js:
  - "node"

branches:
  only:
    - frontend

before_install:
  - openssl aes-256-cbc -K $encrypted_9538a47fef40_key -iv $encrypted_9538a47fef40_iv -in .travis/travis.enc -out .travis/travis -d

after_success:
  - chmod +x .travis/deploy.sh
  - .travis/deploy.sh
