language: cpp
compiler: gcc
branches:
  only:
  - backend
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_9538a47fef40_key -iv $encrypted_9538a47fef40_iv
  -in travis.enc -out travis -d
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install libboost-all-dev
- sudo apt install qt5-default
- sudo apt-get install git
- git clone https://github.com/ipkn/crow
install:
- sudo apt-get install -qq g++-6
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
script:
- cd backend
- qmake
- make
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: PJuzePOm3xlxxwX3gkUzDBqtZudN+rQ7ybSK/y/AWWSO0lVz0PA12ndaYl2qjQIR8cQf2Ag5mEKl1b4dLpltbn9naDIK5+6sb06rDIu6FwpOtCrRBYUTLPOmcqBvMpXGpXRPk+E3T2dZBxNpu0beQM9D+teBjgdu245IpX1hoAxOPWpZFOqgkOJ9MslmPlcKkcjk03yzGiD1rDVGFyG7DYL3cxp9qlLzVI4851GiXJ2MWo6MBZVSeGbj+qpIIePfnYf4IL84HRZJRmqKKh0K+zdUnjvtVmc14GMR96L6jU18OnJiJl+ev2QjDeswtGhC+l1R27guSg2zpuKkHKO915JEN5SUhXR+RX3VpU8Qe//QkPpWX4m5ljZkVYXSNVdmm/IXGhU8rQAOg4UbCAgcENwZIMAa5ljP8LJDijOmu9nDuXJnhVm5nGjluQhWUNqi/1VBxeyFvgHfTGDLPOa1tMXZGrnQ44jvwJpsVR6t+chWgLP2c6FwKHA2kNLAv9C0MMRymGSA5cTPYKvsWlVJcexvNFTmSn+xl6Z3dFIaYOaI7DK//Y5KfkWl2HcG4qOtdiHfCwdytySwOiuyD8g+8yCjCwR30ESOViAwh5StNGJA+UvmTjhCCqH5DmWiMIjR4xCwm3OdNbqpIT8e/h2PJbgLtimqcE9jML+Izp3g1zg=
  app: imagination
  on:
    repo: akapust1n/Imagination
    branch: backend
    run: "./main"
