sudo: required
language: cpp
compiler: gcc

branches:
  only:
  - backend
  - master

matrix:
  include:   
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-6
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  # update envvar config
  - eval $MATRIX_EVAL
  - openssl aes-256-cbc -K $encrypted_9538a47fef40_key -iv $encrypted_9538a47fef40_iv -in .travis/travis.enc -out .travis/travis -d
  - sudo apt-get install libboost-all-dev
  - sudo apt install qt5-default
  - sudo apt-get install git
  - sudo -H pip install conan
  - git clone https://github.com/ipkn/crow

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
  - cd backend
  - conan install .
  - qmake
  - make
  - cd ..
 
after_success:
  - echo -e "Host *\n\tStrictHostKeyChecking no\nUserKnownHostsFile=/dev/null\n" >> ~/.ssh/config
  - chmod +x .travis/deploy.sh
  - .travis/deploy.sh
